import type { Locale, Section } from './i18n'

type MetaInfo = {
  title: string
  description: string
}

const meta: Record<Section, Record<Locale, MetaInfo>> = {
  home: {
    fr: { title: 'Amourette | Terrasse Paris Passy - Restaurant 16eme', description: 'Restaurant Amourette a Passy, Paris 16e. Cuisine francaise traditionnelle, terrasse, musique live. A 5 min de la Tour Eiffel. Ouvert 7j/7.' },
    en: { title: 'Amourette | Terrace Paris Passy - French Restaurant', description: 'Amourette restaurant in Passy, Paris 16th. Traditional French cuisine, terrace, live music. 5 min from Eiffel Tower. Open 7 days.' },
    de: { title: 'Amourette | Terrasse Paris Passy - Franzosisches Restaurant', description: 'Restaurant Amourette in Passy, Paris 16. Traditionelle franzosische Kuche, Terrasse, Live-Musik. 5 Min vom Eiffelturm.' },
    es: { title: 'Amourette | Terraza Paris Passy - Restaurante Frances', description: 'Restaurante Amourette en Passy, Paris 16. Cocina francesa tradicional, terraza, musica en vivo. A 5 min de la Torre Eiffel.' },
    it: { title: 'Amourette | Terrazza Paris Passy - Ristorante Francese', description: 'Ristorante Amourette a Passy, Parigi 16. Cucina francese tradizionale, terrazza, musica dal vivo. A 5 min dalla Torre Eiffel.' },
    pt: { title: 'Amourette | Terraco Paris Passy - Restaurante Frances', description: 'Restaurante Amourette em Passy, Paris 16. Cozinha francesa tradicional, terraco, musica ao vivo. A 5 min da Torre Eiffel.' },
    nl: { title: 'Amourette | Terras Parijs Passy - Frans Restaurant', description: 'Restaurant Amourette in Passy, Parijs 16e. Traditionele Franse keuken, terras, live muziek. 5 min van de Eiffeltoren.' },
    zh: { title: 'Amourette | 巴黎Passy露台 - 法国餐厅', description: 'Amourette餐厅位于巴黎16区Passy。传统法国美食、露台、现场音乐。距埃菲尔铁塔5分钟。' },
    ja: { title: 'Amourette | パリ・パッシーのテラス - フランス料理レストラン', description: 'パリ16区パッシーのAmouretteレストラン。伝統的なフランス料理、テラス、ライブミュージック。エッフェル塔から5分。' },
    ru: { title: 'Amourette | Терраса Париж Пасси - Французский ресторан', description: 'Ресторан Amourette в Пасси, Париж 16-й. Традиционная французская кухня, терраса, живая музыка. 5 мин от Эйфелевой башни.' },
    el: { title: 'Amourette | Βεράντα Παρίσι Passy - Γαλλικό Εστιατόριο', description: 'Εστιατόριο Amourette στο Passy, Παρίσι 16ο. Παραδοσιακή γαλλική κουζίνα, βεράντα, ζωντανή μουσική. 5 λεπτά από τον Πύργο του Άιφελ.' },
    cs: { title: 'Amourette | Terasa Pariz Passy - Francouzska restaurace', description: 'Restaurace Amourette v Passy, Pariz 16. Tradicni francouzska kuchyne, terasa, ziva hudba. 5 min od Eiffelovy veze.' },
  },
  menus: {
    fr: { title: 'Carte et Menus | Amourette Paris Passy', description: 'Decouvrez la carte du restaurant Amourette : entrees, plats, desserts et cocktails. Cuisine francaise de partage a Passy, Paris 16e.' },
    en: { title: 'Menu | Amourette Paris Passy', description: 'Discover Amourette menu: starters, mains, desserts and cocktails. French sharing cuisine in Passy, Paris 16th.' },
    de: { title: 'Speisekarte | Amourette Paris Passy', description: 'Entdecken Sie die Speisekarte von Amourette: Vorspeisen, Hauptgerichte, Desserts und Cocktails.' },
    es: { title: 'Carta y Menus | Amourette Paris Passy', description: 'Descubra la carta de Amourette: entrantes, platos, postres y cocteles. Cocina francesa para compartir.' },
    it: { title: 'Menu | Amourette Parigi Passy', description: 'Scoprite il menu di Amourette: antipasti, piatti, dessert e cocktail. Cucina francese da condividere.' },
    pt: { title: 'Cardapio | Amourette Paris Passy', description: 'Descubra o cardapio do Amourette: entradas, pratos, sobremesas e coqueteis.' },
    nl: { title: 'Menukaart | Amourette Parijs Passy', description: 'Ontdek de menukaart van Amourette: voorgerechten, hoofdgerechten, desserts en cocktails.' },
    zh: { title: '菜单 | Amourette 巴黎 Passy', description: '发现Amourette菜单：前菜、主菜、甜点和鸡尾酒。' },
    ja: { title: 'メニュー | Amourette パリ パッシー', description: 'Amouretteのメニュー：前菜、メイン、デザート、カクテルをご覧ください。' },
    ru: { title: 'Меню | Amourette Париж Пасси', description: 'Откройте меню Amourette: закуски, основные блюда, десерты и коктейли.' },
    el: { title: 'Μενού | Amourette Παρίσι Passy', description: 'Ανακαλύψτε το μενού του Amourette: ορεκτικά, κυρίως πιάτα, επιδόρπια και κοκτέιλ.' },
    cs: { title: 'Jidelni listek | Amourette Pariz Passy', description: 'Objevte jidelni listek Amourette: predkrmy, hlavni chody, dezerty a koktejly.' },
  },
  photos: {
    fr: { title: 'Photos | Amourette Paris Passy', description: 'Galerie photos du restaurant Amourette : terrasse, interieur, plats. Decouvrez l\'ambiance de notre restaurant a Passy.' },
    en: { title: 'Photos | Amourette Paris Passy', description: 'Photo gallery of Amourette restaurant: terrace, interior, dishes. Discover the atmosphere in Passy.' },
    de: { title: 'Fotos | Amourette Paris Passy', description: 'Fotogalerie des Restaurants Amourette: Terrasse, Innenraum, Gerichte.' },
    es: { title: 'Fotografias | Amourette Paris Passy', description: 'Galeria de fotos del restaurante Amourette: terraza, interior, platos.' },
    it: { title: 'Foto | Amourette Parigi Passy', description: 'Galleria fotografica del ristorante Amourette: terrazza, interni, piatti.' },
    pt: { title: 'Fotos | Amourette Paris Passy', description: 'Galeria de fotos do restaurante Amourette: terraco, interior, pratos.' },
    nl: { title: 'Foto\'s | Amourette Parijs Passy', description: 'Fotogalerij van restaurant Amourette: terras, interieur, gerechten.' },
    zh: { title: '照片 | Amourette 巴黎 Passy', description: 'Amourette餐厅照片画廊：露台、内部、菜肴。' },
    ja: { title: '写真 | Amourette パリ パッシー', description: 'Amouretteレストランのフォトギャラリー：テラス、内装、料理。' },
    ru: { title: 'Фото | Amourette Париж Пасси', description: 'Фотогалерея ресторана Amourette: терраса, интерьер, блюда.' },
    el: { title: 'Φωτογραφίες | Amourette Παρίσι Passy', description: 'Φωτογαλερία του εστιατορίου Amourette: βεράντα, εσωτερικός χώρος, πιάτα.' },
    cs: { title: 'Fotografie | Amourette Pariz Passy', description: 'Fotogalerie restaurace Amourette: terasa, interier, pokrmy.' },
  },
  events: {
    fr: { title: 'Evenements et actualites | Amourette Paris', description: 'Decouvrez les evenements du restaurant Amourette a Passy : soirees, reveillons, repas d\'affaires. Reservez votre table.' },
    en: { title: 'Events | Amourette Paris Passy', description: 'Discover Amourette events in Passy: parties, New Year\'s Eve, business dinners. Book your table.' },
    de: { title: 'Veranstaltungen | Amourette Paris Passy', description: 'Entdecken Sie die Veranstaltungen von Amourette: Partys, Silvester, Geschaftsessen.' },
    es: { title: 'Eventos | Amourette Paris Passy', description: 'Descubra los eventos de Amourette: fiestas, Nochevieja, cenas de negocios.' },
    it: { title: 'Eventi | Amourette Parigi Passy', description: 'Scoprite gli eventi di Amourette: feste, Capodanno, cene aziendali.' },
    pt: { title: 'Eventos | Amourette Paris Passy', description: 'Descubra os eventos do Amourette: festas, Reveillon, jantares de negocios.' },
    nl: { title: 'Evenementen | Amourette Parijs Passy', description: 'Ontdek de evenementen van Amourette: feesten, oudejaarsavond, zakelijke diners.' },
    zh: { title: '活动 | Amourette 巴黎 Passy', description: '发现Amourette活动：聚会、新年前夜、商务晚宴。' },
    ja: { title: 'イベント | Amourette パリ パッシー', description: 'Amouretteのイベント：パーティー、大晦日、ビジネスディナー。' },
    ru: { title: 'События | Amourette Париж Пасси', description: 'Откройте события Amourette: вечеринки, Новый год, деловые ужины.' },
    el: { title: 'Εκδηλώσεις | Amourette Παρίσι Passy', description: 'Ανακαλύψτε τις εκδηλώσεις του Amourette: πάρτι, Πρωτοχρονιά, επαγγελματικά δείπνα.' },
    cs: { title: 'Udalosti | Amourette Pariz Passy', description: 'Objevte akce Amourette: vecirky, Silvestr, firemni vecere.' },
  },
  reservation: {
    fr: { title: 'Reserver une table | Amourette Paris Passy', description: 'Reservez votre table au restaurant Amourette a Passy, Paris 16e. Terrasse disponible. Ouvert 7j/7, 11h30-02h00.' },
    en: { title: 'Book a Table | Amourette Paris Passy', description: 'Book your table at Amourette restaurant in Passy, Paris 16th. Terrace available. Open 7 days, 11:30am-2:00am.' },
    de: { title: 'Tisch reservieren | Amourette Paris Passy', description: 'Reservieren Sie Ihren Tisch im Restaurant Amourette in Passy, Paris 16.' },
    es: { title: 'Reservar mesa | Amourette Paris Passy', description: 'Reserve su mesa en el restaurante Amourette en Passy, Paris 16.' },
    it: { title: 'Prenotare un tavolo | Amourette Parigi Passy', description: 'Prenotate il vostro tavolo al ristorante Amourette a Passy, Parigi 16.' },
    pt: { title: 'Reservar mesa | Amourette Paris Passy', description: 'Reserve sua mesa no restaurante Amourette em Passy, Paris 16.' },
    nl: { title: 'Tafel reserveren | Amourette Parijs Passy', description: 'Reserveer uw tafel bij restaurant Amourette in Passy, Parijs 16e.' },
    zh: { title: '预订餐桌 | Amourette 巴黎 Passy', description: '在巴黎16区Passy的Amourette餐厅预订餐桌。' },
    ja: { title: 'テーブル予約 | Amourette パリ パッシー', description: 'パリ16区パッシーのAmouretteレストランでテーブルを予約。' },
    ru: { title: 'Забронировать столик | Amourette Париж Пасси', description: 'Забронируйте столик в ресторане Amourette в Пасси, Париж 16-й.' },
    el: { title: 'Κράτηση τραπεζιού | Amourette Παρίσι Passy', description: 'Κλείστε τραπέζι στο εστιατόριο Amourette στο Passy, Παρίσι 16ο.' },
    cs: { title: 'Rezervace stolu | Amourette Pariz Passy', description: 'Rezervujte si stul v restauraci Amourette v Passy, Pariz 16.' },
  },
  privatisations: {
    fr: { title: 'Privatisations | Amourette Paris Passy', description: 'Privatisez le restaurant Amourette pour vos evenements. Jusqu\'a 60 personnes en hiver, 200 en ete. Contactez-nous.' },
    en: { title: 'Private Events | Amourette Paris Passy', description: 'Privatize Amourette restaurant for your events. Up to 60 guests in winter, 200 in summer. Contact us.' },
    de: { title: 'Privatisierung | Amourette Paris Passy', description: 'Privatisieren Sie das Restaurant Amourette fur Ihre Events. Bis zu 60 Gaste im Winter, 200 im Sommer.' },
    es: { title: 'Privatizaciones | Amourette Paris Passy', description: 'Privatice el restaurante Amourette para sus eventos. Hasta 60 invitados en invierno, 200 en verano.' },
    it: { title: 'Privatizzazioni | Amourette Parigi Passy', description: 'Privatizzate il ristorante Amourette per i vostri eventi. Fino a 60 ospiti in inverno, 200 in estate.' },
    pt: { title: 'Privatizacoes | Amourette Paris Passy', description: 'Privatize o restaurante Amourette para seus eventos. Ate 60 convidados no inverno, 200 no verao.' },
    nl: { title: 'Privatisering | Amourette Parijs Passy', description: 'Privatiseer restaurant Amourette voor uw evenementen. Tot 60 gasten in de winter, 200 in de zomer.' },
    zh: { title: '私人活动 | Amourette 巴黎 Passy', description: '为您的活动包下Amourette餐厅。冬季最多60位客人，夏季200位。' },
    ja: { title: '貸切 | Amourette パリ パッシー', description: 'イベントのためにAmouretteレストランを貸切。冬は60名まで、夏は200名まで。' },
    ru: { title: 'Приватизация | Amourette Париж Пасси', description: 'Арендуйте ресторан Amourette для ваших мероприятий. До 60 гостей зимой, 200 летом.' },
    el: { title: 'Ιδιωτικές Εκδηλώσεις | Amourette Παρίσι Passy', description: 'Κλείστε αποκλειστικά το εστιατόριο Amourette. Έως 60 άτομα τον χειμώνα, 200 το καλοκαίρι.' },
    cs: { title: 'Privatizace | Amourette Pariz Passy', description: 'Pronajmete si restauraci Amourette pro sve akce. Az 60 hostu v zime, 200 v lete.' },
  },
  legal: {
    fr: { title: 'Mentions legales | Amourette Paris Passy', description: 'Mentions legales du site amourette-passy.fr. Editeur : DELESSERT, SIRET 88413566600011.' },
    en: { title: 'Legal Notices | Amourette Paris Passy', description: 'Legal notices for amourette-passy.fr. Publisher: DELESSERT, SIRET 88413566600011.' },
    de: { title: 'Impressum | Amourette Paris Passy', description: 'Impressum von amourette-passy.fr. Herausgeber: DELESSERT, SIRET 88413566600011.' },
    es: { title: 'Notas legales | Amourette Paris Passy', description: 'Notas legales de amourette-passy.fr. Editor: DELESSERT, SIRET 88413566600011.' },
    it: { title: 'Note legali | Amourette Parigi Passy', description: 'Note legali di amourette-passy.fr. Editore: DELESSERT, SIRET 88413566600011.' },
    pt: { title: 'Avisos legais | Amourette Paris Passy', description: 'Avisos legais de amourette-passy.fr. Editor: DELESSERT, SIRET 88413566600011.' },
    nl: { title: 'Juridische vermeldingen | Amourette Parijs Passy', description: 'Juridische vermeldingen van amourette-passy.fr. Uitgever: DELESSERT, SIRET 88413566600011.' },
    zh: { title: '法律信息 | Amourette 巴黎 Passy', description: 'amourette-passy.fr法律信息。出版商：DELESSERT。' },
    ja: { title: '法的情報 | Amourette パリ パッシー', description: 'amourette-passy.frの法的情報。発行者：DELESSERT。' },
    ru: { title: 'Юридическая информация | Amourette Париж Пасси', description: 'Юридическая информация amourette-passy.fr. Издатель: DELESSERT.' },
    el: { title: 'Νομικές πληροφορίες | Amourette Παρίσι Passy', description: 'Νομικές πληροφορίες του amourette-passy.fr. Εκδότης: DELESSERT.' },
    cs: { title: 'Pravni informace | Amourette Pariz Passy', description: 'Pravni informace amourette-passy.fr. Vydavatel: DELESSERT.' },
  },
  contact: {
    fr: { title: 'Contact et informations | Amourette Paris Passy', description: 'Adresse, telephone et acces au restaurant Amourette : 10 Boulevard Delessert, 75016 Paris. Metro Passy / Trocadero.' },
    en: { title: 'Contact & Directions | Amourette Paris Passy', description: 'Address, phone and directions to Amourette: 10 Boulevard Delessert, 75016 Paris. Metro Passy / Trocadero.' },
    de: { title: 'Kontakt & Anfahrt | Amourette Paris Passy', description: 'Adresse, Telefon und Anfahrt zum Amourette: 10 Boulevard Delessert, 75016 Paris.' },
    es: { title: 'Contacto y direccion | Amourette Paris Passy', description: 'Direccion, telefono y como llegar a Amourette: 10 Boulevard Delessert, 75016 Paris.' },
    it: { title: 'Contatti e indicazioni | Amourette Parigi Passy', description: 'Indirizzo, telefono e indicazioni per Amourette: 10 Boulevard Delessert, 75016 Parigi.' },
    pt: { title: 'Contacto e direcoes | Amourette Paris Passy', description: 'Endereco, telefone e direcoes para o Amourette: 10 Boulevard Delessert, 75016 Paris.' },
    nl: { title: 'Contact & route | Amourette Parijs Passy', description: 'Adres, telefoon en route naar Amourette: 10 Boulevard Delessert, 75016 Parijs.' },
    zh: { title: '联系方式 | Amourette 巴黎 Passy', description: '地址、电话和前往Amourette的交通方式：10 Boulevard Delessert, 75016 Paris。' },
    ja: { title: 'アクセス・お問合せ | Amourette パリ パッシー', description: '住所、電話、Amouretteへのアクセス：10 Boulevard Delessert, 75016 Paris。' },
    ru: { title: 'Контакты | Amourette Париж Пасси', description: 'Адрес, телефон и как добраться до Amourette: 10 Boulevard Delessert, 75016 Paris.' },
    el: { title: 'Επικοινωνία | Amourette Παρίσι Passy', description: 'Διεύθυνση, τηλέφωνο και οδηγίες για το Amourette: 10 Boulevard Delessert, 75016 Παρίσι.' },
    cs: { title: 'Kontakt | Amourette Pariz Passy', description: 'Adresa, telefon a jak se dostat do Amourette: 10 Boulevard Delessert, 75016 Pariz.' },
  },
  privacy: {
    fr: { title: 'Politique de confidentialite | Amourette Paris Passy', description: 'Politique de protection des donnees personnelles du restaurant Amourette a Passy, Paris.' },
    en: { title: 'Privacy Policy | Amourette Paris Passy', description: 'Privacy and data protection policy for Amourette restaurant, Passy, Paris.' },
    de: { title: 'Datenschutzrichtlinie | Amourette Paris Passy', description: 'Datenschutzrichtlinie des Restaurants Amourette in Passy, Paris.' },
    es: { title: 'Politica de privacidad | Amourette Paris Passy', description: 'Politica de proteccion de datos del restaurante Amourette en Passy, Paris.' },
    it: { title: 'Informativa sulla privacy | Amourette Parigi Passy', description: 'Informativa sulla privacy del ristorante Amourette a Passy, Parigi.' },
    pt: { title: 'Politica de privacidade | Amourette Paris Passy', description: 'Politica de protecao de dados do restaurante Amourette em Passy, Paris.' },
    nl: { title: 'Privacybeleid | Amourette Parijs Passy', description: 'Privacybeleid van restaurant Amourette in Passy, Parijs.' },
    zh: { title: '隐私政策 | Amourette 巴黎 Passy', description: 'Amourette餐厅隐私和数据保护政策。' },
    ja: { title: 'プライバシーポリシー | Amourette パリ パッシー', description: 'Amouretteレストランのプライバシーとデータ保護ポリシー。' },
    ru: { title: 'Политика конфиденциальности | Amourette Париж Пасси', description: 'Политика защиты данных ресторана Amourette в Пасси, Париж.' },
    el: { title: 'Πολιτική απορρήτου | Amourette Παρίσι Passy', description: 'Πολιτική προστασίας δεδομένων του εστιατορίου Amourette στο Passy, Παρίσι.' },
    cs: { title: 'Zasady ochrany soukromi | Amourette Pariz Passy', description: 'Zasady ochrany osobnich udaju restaurace Amourette v Passy, Pariz.' },
  },
  cookies: {
    fr: { title: 'Politique de cookies | Amourette Paris Passy', description: 'Politique d\'utilisation des cookies sur le site amourette-passy.fr.' },
    en: { title: 'Cookie Policy | Amourette Paris Passy', description: 'Cookie usage policy for amourette-passy.fr website.' },
    de: { title: 'Cookie-Richtlinie | Amourette Paris Passy', description: 'Cookie-Richtlinie der Website amourette-passy.fr.' },
    es: { title: 'Politica de cookies | Amourette Paris Passy', description: 'Politica de uso de cookies del sitio amourette-passy.fr.' },
    it: { title: 'Politica dei cookie | Amourette Parigi Passy', description: 'Politica di utilizzo dei cookie del sito amourette-passy.fr.' },
    pt: { title: 'Politica de cookies | Amourette Paris Passy', description: 'Politica de utilizacao de cookies do site amourette-passy.fr.' },
    nl: { title: 'Cookiebeleid | Amourette Parijs Passy', description: 'Cookiebeleid van de website amourette-passy.fr.' },
    zh: { title: 'Cookie政策 | Amourette 巴黎 Passy', description: 'amourette-passy.fr网站Cookie使用政策。' },
    ja: { title: 'Cookieポリシー | Amourette パリ パッシー', description: 'amourette-passy.frウェブサイトのCookie使用ポリシー。' },
    ru: { title: 'Политика cookies | Amourette Париж Пасси', description: 'Политика использования cookies на сайте amourette-passy.fr.' },
    el: { title: 'Πολιτική cookies | Amourette Παρίσι Passy', description: 'Πολιτική χρήσης cookies του ιστοτόπου amourette-passy.fr.' },
    cs: { title: 'Zasady cookies | Amourette Pariz Passy', description: 'Zasady pouzivani cookies na webu amourette-passy.fr.' },
  },
  accessibility: {
    fr: { title: 'Accessibilite | Amourette Paris Passy', description: 'Declaration d\'accessibilite du site amourette-passy.fr. Conformite WCAG 2.1 Niveau AA.' },
    en: { title: 'Accessibility | Amourette Paris Passy', description: 'Accessibility statement for amourette-passy.fr. WCAG 2.1 Level AA compliance.' },
    de: { title: 'Barrierefreiheit | Amourette Paris Passy', description: 'Barrierefreiheitserklarung von amourette-passy.fr. WCAG 2.1 Level AA.' },
    es: { title: 'Accesibilidad | Amourette Paris Passy', description: 'Declaracion de accesibilidad de amourette-passy.fr. Conformidad WCAG 2.1 Nivel AA.' },
    it: { title: 'Accessibilita | Amourette Parigi Passy', description: 'Dichiarazione di accessibilita di amourette-passy.fr. Conformita WCAG 2.1 Livello AA.' },
    pt: { title: 'Acessibilidade | Amourette Paris Passy', description: 'Declaracao de acessibilidade de amourette-passy.fr. Conformidade WCAG 2.1 Nivel AA.' },
    nl: { title: 'Toegankelijkheid | Amourette Parijs Passy', description: 'Toegankelijkheidsverklaring van amourette-passy.fr. WCAG 2.1 Niveau AA.' },
    zh: { title: '无障碍 | Amourette 巴黎 Passy', description: 'amourette-passy.fr无障碍声明。WCAG 2.1 AA级合规。' },
    ja: { title: 'アクセシビリティ | Amourette パリ パッシー', description: 'amourette-passy.frのアクセシビリティ声明。WCAG 2.1レベルAA準拠。' },
    ru: { title: 'Доступность | Amourette Париж Пасси', description: 'Заявление о доступности amourette-passy.fr. Соответствие WCAG 2.1 уровень AA.' },
    el: { title: 'Προσβασιμότητα | Amourette Παρίσι Passy', description: 'Δήλωση προσβασιμότητας του amourette-passy.fr. Συμμόρφωση WCAG 2.1 Επίπεδο AA.' },
    cs: { title: 'Pristupnost | Amourette Pariz Passy', description: 'Prohlaseni o pristupnosti amourette-passy.fr. Soulad s WCAG 2.1 uroven AA.' },
  },
}

export function getPageMeta(section: Section, locale: Locale): MetaInfo {
  return meta[section][locale]
}
